server:
  port: 8085

spring:
  datasource:
    username: root
    password: sp^Ea1aaE3YN
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&serverTimezone=UTC
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru